version: '2'

services:
  my-payment-demo:
    build: .
    ports:
      - 3000:3000
    links:
      - redis
    command: bash -c "/usr/local/bin/npm run start:example"
    environment:
      - DEMO_REDIS=redis
  redis:
    image: redis:3.2.0-alpine
    command: redis-server --appendonly yes